---
apiVersion: homelab.io/v1alpha1
kind: SSHAccessGrant
metadata:
  name: desktop-matt
spec:
  serverRef:
    name: desktop
  loginUser: matt
  credential:
    generatedKeyPair:
      algorithm: ed25519
      keyName: matt
      secretStoreRef:
        name: openbao
