---
apiVersion: homelab.io/v1alpha1
kind: InventoryCaptureGroup
metadata:
  name: servers
spec:
  selector:
    matchKinds:
      - apiVersion: homelab.io/v1alpha1
        kind: Server

  groups:
    - name: workstations
      selector:
        matchLabels:
          homelab.io/role: workstation

  groupVars:
    all:
      ansible_user: matt
      ansible_ssh_private_key_file: /home/matt/.ssh/id_ed25519

    workstations:
      desktop_environment: true