---
apiVersion: homelab.io/v1alpha1
kind: SecretStore
metadata:
  name: openbao
spec:
  provider:
    openBao:
      address: http://openbao:8200
      kvV2Mount: kv2
      keyPrefix: secrets
      authentication:
        tokenFile: /run/openbao/token
