---
apiVersion: homelab.io/v1alpha1
kind: Server
metadata:
  name: localhost
  labels:
    homelab.io/role: testing
spec:
  machineSelector:
    location:
      lldp_port: bridge/ether1337
      switch_mac: aa:bb:cc:dd:ee:ff
  networking:
    management:
      interfaceSelector:
        attachedAtMachineLocation: true
      addressSelector:
        family: ipv4
        subnet: 127.0.0.1/24
