---
apiVersion: homelab.io/v1alpha1
kind: InventoryCaptureGroup
metadata:
  name: servers
spec:
  selector:
    matchKinds:
      - apiVersion: homelab.io/v1alpha1
        kind: Server
    matchLabels:
      homelab.io/role: workstation

  groups:
    - name: workstations
      selector:
        matchLabels:
          homelab.io/role: workstation

  groupVarsRef:
    name: servers-group-vars

    workstations:
      desktop_environment: true
