---
apiVersion: homelab.io/v1alpha1
kind: InventoryCaptureGroup
metadata:
  name: servers
spec:
  selector:
    matchKinds:
      - apiVersion: homelab.io/v1alpha1
        kind: Server
    matchLabels:
      homelab.io/role: workstation

  groups:
    - name: workstations
      selector:
        matchLabels:
          homelab.io/role: workstation

  groupVars:
    all:
      ansible_user: ansible
      ansible_ssh_private_key_file: /home/ansible/.ssh/id_github

      host_data_path: /srv/homelab

      git_stigmergy_repo: "git@github.com:asdf57/stigmergy.git"
      git_webhook_repo: "git@github.com:asdf57/webhook-server.git"
      git_inventory_repo: "git@github.com:asdf57/inventory.git"
      git_ansible_roles_repo: "git@github.com:asdf57/ansible-roles.git"
      git_stigmergy_branch: main
      git_webhook_branch: main
      git_inventory_branch: main
      git_ansible_roles_branch: main

      nginx_ipv4: "10.0.2.123"
      openbao_ipv4: "10.0.2.125"
      openbao_url: "https://vault.ryuugu.dev"
      openbao_api_fqdn: "vault-api.ryuugu.dev"

      concourse_fqdn: "ci.ryuugu.dev"

    workstations:
      desktop_environment: true
