---
apiVersion: homelab.io/v1alpha1
kind: InventoryCaptureGroup
metadata:
  name: platform
spec:
  selector:
    matchKinds:
      - apiVersion: homelab.io/v1alpha1
        kind: Server
    matchLabels:
      homelab.io/role: platform-config

  groupVarsRef:
    name: platform-group-vars
