apiVersion: homelab.io/v1alpha1
kind: InventoryCaptureGroup
metadata: {name: ssh-managed}
spec:
  selector:
    matchKinds: [{apiVersion: homelab.io/v1alpha1, kind: Server}]
    matchLabels: {homelab.io/ssh-management: enabled}
  groupVars:
    all:
      ansible_user: ansible
      ansible_become: true
      provision_disable_eee: true
      storage:
        partitions:
          - {fs_type: efi, alloc_type: size, size: 512, flags: [boot, esp]}
          - {fs_type: swap, alloc_type: size, size: 2048, flags: []}
          - {fs_type: ext4, alloc_type: percentage, size: 100, flags: []}
