---
apiVersion: homelab.io/v1alpha1
kind: GitRepository
metadata:
  name: ansible-inventory
spec:
  url: git@github.com:asdf57/inventory.git
  branch: main
  authentication:
    sshKeyPairRef: git-ssh-key
  commit:
    authorName: Stigmergy
    authorEmail: stigmergy@homelab.local
    messageTemplate: "Update {{ .Publication.metadata.name }}"
